export GITHOME=$HOME/Git
export PROJECTHOME=$GITHOME/Projects
export CONFHOME=$GITHOME/ConFiles
export SHCONFHOME=$CONFHOME/sh
export EMACSCONFHOME=$CONFHOME/emacs
export ELISPCONFHOME=$EMACSCONFHOME/elisp
source $SHCONFHOME/alias.sh
