export GITHOME=$HOME/Git
export PROJECTHOME=$GITHOME/Projects
export CONFHOME=$GITHOME/ConFiles
export BASHCONFHOME=$CONFHOME/bash
export ZSHCONFHOME=$CONFHOME/zsh
export EMACSCONFHOME=$CONFHOME/emacs
export ELISPCONFHOME=$EMACSCONFHOME/elisp
source alias.sh
