(require 'company-c-headers)
(add-to-list 'company-c-headers-path-system "/usr/include/c++/7.3.0/")
(add-to-list 'company-c-headers-path-system "/usr/include/x86_64-linux-gnu/")
(add-to-list 'company-c-headers-path-system "/usr/include/x86_64-linux-gnu/c++/7.3.0/")
(setq c-basic-offset 2)
